### ISSUE TITLE
Shore/Foam instructions?

### ISSUE THREAD

**Issue by PascalSoftwares** [CthulhuBaba/LiteWater#1]
You have forming effects in example video, but it is hard to figure out how to set the value for setup project.
It would be appreciated to add shore settings guide in 'Integration' section of README.

**Comment by CthulhuBaba** [comment]
Hello. For reasons beyond my control, I haven't been able to deal with Flax
for a while. I am sorry about that. I don't have the opportunity to run and
test the project right now, but I can give information about shore/foam
settings.

You can access the settings of both from the Instance settings. As in the
picture;
[image: shore1.jpg]

![shore1](https://github.com/CthulhuBaba/LiteWater/assets/31192693/59ee0f68-afb0-486e-b21c-349d4378005d)


If you want to change their textures, you can directly open "WaterShader"
instead of Instance and access the settings as in the picture. They're in
the upper right corner.
[image: shore2.jpg]
![shore2](https://github.com/CthulhuBaba/LiteWater/assets/31192693/f394d5c3-7b57-453f-9b6d-b1d1c22b4387)


I hope I could help.

Regards,
Emre

**Comment by PascalSoftwares** [comment]
Sadly it seems hard to figure out how to set the values to make 'shore foam' around other actors like showcase video...
How the water material 'recognizes' the objects located adjacent to itself?

**Comment by CthulhuBaba** [comment]
Via depth camera. The depth camera colors the scene according to the selected depth value and transfers it to a texture. Water material also creates the shore effect according to the colors in this texture.

It looks like this:
![depth_shore](https://github.com/CthulhuBaba/LiteWater/assets/31192693/7fda8b85-9eac-4930-817b-42393be23d86)



The extent of the red zone can be adjusted with the "SHORE DEPTH/DEEP" variable.

**Comment by PascalSoftwares** [comment]
Uh.... 

Isn't it required to add **'ground things'** to Depth Camera actor -> Custom Depth script -> Actors list to be **'Recognized by depth camera'**?

I tweaked Refraction Depth/ShoreDeep etc of material instance in vain, 
but depth camera had only one parameter can be modified, and it made some difference...

**Comment by CthulhuBaba** [comment]
When you leave the actor list blank/empty, depth camera recognizes all actors in the scene by default. All you have to do is prevent the depth camera from rendering the water. For this, just use "layer" as I explained on the home page.

**Comment by PascalSoftwares** [comment]
Then something is still not configured properly for me...
Just adding certain object / emptying all makes difference in form creation around the object in my set of parameters.
Of course layer settings are already made following your guides.

**Comment by CthulhuBaba** [comment]
When Flax 1.6 was released, there was a bug related to "DrawSceneDepth" in the engine. After I reported it, the problem was fixed with dailybuilds. Here is the [report](https://github.com/FlaxEngine/FlaxEngine/issues/1253).

I thought this bugfix was also added to the 1.6 installation/release package (**_that's why this issue completely slipped my mind_**) but obviously it wasn't. 

I think this is the reason for the trouble you are experiencing.

I believe that if you install the MasterBranch version of the engine, the problem will go away. For this, you can use the Flax interface as follows.
![dailybuild](https://github.com/CthulhuBaba/LiteWater/assets/31192693/1603837e-da64-4df5-80f5-28ca2462c992)

**I'm sorry I didn't think of this solution before. I completely forgot about that bug because I thought the bug fix in question was added to 1.6.**

Good luck!
